### PR TITLE
fix: Build JupyterLab extensions in postBuild

### PR DESCRIPTION
**Pull request by matthewfeickert**
Build the required JupyterLab extensions in `postBuild` to avoid getting a warning upon entering JupyterLab on Binder launch (mentioned by @cranmer in PR #1).

Example: [Binder](https://mybinder.org/v2/gh/cranmer/stats-ds-book/master?urlpath=lab/tree/book)

### CODE REVIEW

**Comment by matthewfeickert** [comment]
@cranmer This is ready for review.

**Comment by cranmer** [comment]
Thanks!

**Comment by cranmer** [comment]
Hmm, I didn't realize until now that building the jupyter-book broke after merging this PR
See: https://github.com/cranmer/stats-ds-book/actions

Something happened so now it gives error when building book:
```ImportError: cannot import name 'MdParserConfig' from 'myst_parser.main' (/opt/hostedtoolcache/Python/3.8.5/x64/lib/python3.8/site-packages/myst_parser/main.py)
18
##[error]Process completed with exit code 1.```
I haven't tracked down yet why yet, but seems to be due to change in postBuild messing with environment.

**Comment by cranmer** [comment]
I'm not sure if is something about the postBuild or if it's a version change or something. Still searching.

**Comment by cranmer** [comment]
Commenting out those lines in `postBuild` didn't help
I see in logs:

**Before**
```
2020-08-21T17:05:41.1957713Z myst-nb                       0.8.5
2020-08-21T17:05:41.1958439Z myst-parser                   0.11.2
```

**After** 
```
2020-08-26T01:20:28.5559051Z myst-nb                       0.9.1
2020-08-26T01:20:28.5559474Z myst-parser                   0.11.2
```

but seems strange that jupyter book wouldn't pick a compatible version of myst

**Comment by cranmer** [comment]
Ah yes, maybe it's b/c requirements had 
```
myst-parser~=0.11.1  # Restrict range to satisfy myst-nb
```
Trying that out

**Comment by cranmer** [comment]
Well now the versions are 
```
myst-nb                       0.8.5
myst-parser                   0.12.2
```
and it's still dying. https://github.com/cranmer/stats-ds-book/runs/1029475479?check_suite_focus=true

**Comment by cranmer** [comment]
ok, fixed if I add 
```
myst-nb~=0.8.5
myst-parser~=0.11.1  # Restrict range to satisfy myst-nb
```
to the requirements, but that's kind of annoying. I'm kind of confused what is leading to that problem. I would have guessed that the right versions would be picked up.

**Comment by matthewfeickert** [comment]
> I'm kind of confused what is leading to that problem. I would have guessed that the right versions would be picked up.

@cranmer PR #3 should clean this up.
